language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarqube:
    organization: mavaze-github
    token:
      secure: SWbOavsMcXLesjLBc+fQuzsgqDCdeFESwiTuQsHTJFQmH3aU80v5OQOiMZ64EZjrptFjnLN9UN0Ma5M6MaleTYMeqVoBFg8Loimb+gZCxOG7njnWrsNI+31DkOlrhadQiG8Jy4XkunVvrGM1R62sX89Klz5YYnswXj6vxnkwvHVBN/EigswuQqKQhSvVsdd03XeO9eAj455vxHY/8vSHo1f7TDBdqlDHs2ufZK9zfCuFpEUcTPD59A6SEdjFsnUCdYCbnGmrSKD6T6gJ4j9vx8uWklWrYK/z1pkUtVkKNNZ87i2fH0kxmxbzmTtwINer8tPf54xatdiMePBG3H+/+JsH4FNVpdHGQQGsRO2OYDPeMo3ctNGkHqhIL+7OLRXMAKGv0XSEbFkVS82olu85jcROJQjUPZgDSc3mHUTPfaqfduA8v7ro9cXL+zZ4BCnDcOtBznW+IEmMdqXSgygh+8/eB8VL+HMWo4KKcdaiFP+P4RznERWJBzpMaJ62ap3LWyTkAv/b1Mp3wvJ3SHHI74iL7fbbrUhuregxsSejQpCZs/0dyyxUi0jhGThfv1HEsTxvGfblC6PwmDi1NDVIIc7+VvMMbU08n1JVDA720oGfgoJCoKRJC84RotRhPlXHOKhESk+RRnChcKQ7pJnI4cnj9Ims6ilfAaS1MW9m5qE=
install:
- mvn dependency:go-offline
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: iawzZM+M+B+wSYSWBDqjfJDDby+egmG5PHBb6WyZzALtkF0HaiLMMBDChG2u/cM83LIOVAobR3mIATxiysym7f+CnZygcwbHfr/MG6CrB7lExoCKEHboLdK4pxvE+DcsYr+3HpSuApAHrf8aUOmtmuc8D/CIWj38GmGjf7wU6V0NEV2on3aYQ2BE+8Uj15mDSxdfKGBD3x7vS0x5jycRDkPxpbNbgpGm3pSqJWDw7uRpbbP6S/rhY/++dslermmLzfZvz3V5hzN5w8o93fcOb6YPKspS5+VBor1VzwKmDM96mHIFvSJmltGEGRbQvgWqJ3y6FcQjNEDHFbd/OIRDLdGRVBnfpFZoVTdS5a8ud25r5nKO4K72HFNqPphH+M6pSGhQrjhrkf7bIJaWQUrC2gac9xaAry2g50+soWCC79Voty6MZ/YvavfKeU4OP/z2ePfSjQGSA7i01tTjkeX3b/dfP1gcv5HuATyIIrNxC+0VjtTJSDWJ+S0WSs+xHJbUKuSpv9O8gSYRQq7usZGxny4HWNbCkU60rXoH3J6Pe4o+j9L3VRqkvuw7P6ZgWXaAvLgdte+N2jNtIunDYSU7Ax/gsbB7dRRL59HFTd4t2rG7TkBWIPqfW8IuBj59WND8s/gHPQnz7pKuPRKqvX+lgATTzBS3hTVxFPtG1/NdQ78=
